### ISSUE TITLE
本机打开页面后提示 The script has an unsupported MIME type ('application/octet-stream'). 导致sw文件无法安装

### ISSUE THREAD

**Issue by rurusgit** [lavas-project/lavas-template-vue-ssr#7]
lavas init 新搭建工程并安装好需要的组件后，执行
npm run build;
npm run start;

之后打开localhost:8080 会出现
The script has an unsupported MIME type ('application/octet-stream')
请问下如何处理，多谢:)

截图如下：
![image](https://user-images.githubusercontent.com/24243075/30999054-24e3d07a-a505-11e7-841d-2d507cd1f367.png)

![image](https://user-images.githubusercontent.com/24243075/30999063-3be36baa-a505-11e7-88bf-5d2c34a14e65.png)

**Comment by zoumiaojiang** [comment]
看起来是不是什么浏览器插件导致的问题，如果你使用的是 chrome 浏览器的话，你试试隐身模式打开看看～

**Comment by rurusgit** [comment]
@zoumiaojiang 多谢，可以了，其实是必须要npm update  一次才行
